function [joints]=cartesianPinkieOrient(poseIn,bariM,bariS,baseM,baseS,scaleFactor,target_hand)
    pinkieIn=[poseIn(1,4),poseIn(2,4),poseIn(3,4)];
    pose=(pinkieIn-bariM)*scaleFactor;
    rotM=tform2rotm(baseM);
    rotS=tform2rotm(baseS);
    pose1=(rotM\pose')';
    pose2=(rotS*pose1')';
    pose3=pose2+bariS;
    pose=(baseS\[pose3, 1]')';
    pose(4)=[];
    rotpose=tform2rotm(poseIn);
    rotpose=rotM\rotpose;
    target_pose=rotm2tform(rotpose);
    target_pose(1,4)=pose(1);
    target_pose(2,4)=pose(2);
    target_pose(3,4)=pose(3);
    quat=rotm2quat(rotpose);
    %%%%inverse kinematics
    ik = generalizedInverseKinematics;
    ik.RigidBodyTree = target_hand{5};
    ik.ConstraintInputs = {'position','joint','orientation'};
    % ik_thumb.SolverParameters.SolutionTolerance = 1e-12;
    poseTg = constraintPositionTarget(target_hand{5}.BodyNames{end});
    poseTg.TargetPosition = pose;
    poseTg.Weights=5;
    jointConst = constraintJointBounds(target_hand{5});
    jointConst.Bounds = [-deg2rad(30) deg2rad(30); -pi/2 pi/2;   0 pi/2; 0 pi/2];
    jointConst.Weights=[100,100,100,100];
    orientTg=constraintOrientationTarget(target_hand{5}.BodyNames{end});
    orientTg.TargetOrientation=quat;
    initialguess = homeConfiguration(target_hand{5});
    [configSoln,solnInfo] = ik(initialguess,poseTg,jointConst,orientTg);
    [q1,q2,q3,q4] = configSoln.JointPosition;
    joints = [q1,q2,q3,q4];
end